// AUTH
export const AUTH_LOADING = "AUTH_LOADING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE"
export const UPDATE_USER_IN_STORE = "UPDATE_USER_IN_STORE"

// INIT
export const ADD_TOKEN_TO_STATE = "ADD_TOKEN_TO_STATE"
export const QUERY_USER_BY_TOKEN = "QUERY_USER_BY_TOKEN"
export const QUERYING_USER_BY_TOKEN = "QUERYING_USER_BY_TOKEN"
export const QUERYING_USER_BY_TOKEN_SUCCESS = "QUERYING_USER_BY_TOKEN_SUCCESS"
export const QUERYING_USER_BY_TOKEN_ERROR = "QUERYING_USER_BY_TOKEN_ERROR"

// TRIPS
export const LOADING_TRIPS = "LOADING_TRIPS"
export const LOADING_TRIPS_SUCCESS = "LOADING_TRIPS_SUCCESS"
export const LOADING_TRIPS_ERROR = "LOADING_TRIPS_ERROR"
export const LOADING_ARCHIVED_TRIPS = "LOADING_ARCHIVED_TRIPS"
export const LOADING_ARCHIVED_TRIPS_SUCCESS = "LOADING_ARCHIVED_TRIPS_SUCCESS"
export const LOADING_ARCHIVED_TRIPS_ERROR = "LOADING_ARCHIVED_TRIPS_ERROR"
export const CREATING_TRIP = "CREATING_TRIP"
export const CREATING_TRIP_SUCCESS = "CREATING_TRIP_SUCCESS"
export const CREATING_TRIP_ERROR = "CREATING_TRIP_ERROR"
export const CREATING_WAYPOINT = "CREATING_WAYPOINT"
export const DELETING_TRIP = "DELETING_TRIP"
export const DELETING_TRIP_SUCCESS = "DELETING_TRIP_SUCCESS"
export const DELETING_TRIP_ERROR = "DELETING_TRIP_ERROR"
export const GET_SINGLE_TRIP = "GET_SINGLE_TRIP"
export const TOGGLE_ARCHIVE_TRIP = "TOGGLE_ARCHIVE_TRIP"
export const TOGGLE_ARCHIVE_TRIP_SUCCESS = "TOGGLE_ARCHIVE_TRIP_SUCCESS"
export const TOGGLE_ARCHIVE_TRIP_ERROR = "TOGGLE_ARCHIVE_TRIP_ERROR"
export const REPEAT_TRIP = "REPEAT_TRIP"
export const REPEAT_TRIP_SUCCESS = "REPEAT_TRIP_SUCCESS"
export const REPEAT_TRIP_ERROR = "REPEAT_TRIP_ERROR"
export const EDIT_TRIP = "EDIT_TRIP"
export const EDIT_TRIP_SUCCESS = "EDIT_TRIP_SUCCESS"
export const EDIT_TRIP_ERROR = "EDIT_TRIP_ERROR"
export const START_TRIP = "START_TRIP"
export const START_TRIP_SUCCESS = "START_TRIP_SUCCESS"
export const START_TRIP_ERROR = "START_TRIP_ERROR"
export const ADD_TRIP_TIME_LIMIT = "ADD_TRIP_TIME_LIMIT"
export const ADD_TRIP_TIME_LIMIT_SUCCESS = "ADD_TRIP_TIME_LIMIT_SUCCESS"
export const ADD_TRIP_TIME_LIMIT_ERROR = "ADD_TRIP_TIME_LIMIT_ERROR"
export const TOGGLE_VISIBILITY_OFF = "TOGGLE_VISIBILITY_OFF"
export const TOGGLE_VISIBILITY_ON = "TOGGLE_VISIBILITY_ON"

export const REMOVE_ACTIVE_TRIP = "REMOVE_ACTIVE_TRIP"

// BILLING
export const INIT_NEW_SUBSCRIPTION = "INIT_NEW_SUBSCRIPTION"
export const SUBSCRIBE_PENDING = "SUBSCRIBE_PENDING"
export const SUBSCRIBE_SUCCESS = "SUBSCRIBE_SUCCESS"
export const SUBSCRIBE_FAIL = "SUBSCRIBE_FAIL"
export const INIT_NEW_CANCELLATION = "INIT_NEW_CANCELLATION"
export const CANCEL_SUBSCRIPTION_SUCCESS = "CANCEL_SUBSCRIPTION_SUCCESS"
export const CANCEL_SUBSCRIPTION_FAIL = "CANCEL_SUBSCRIPTION_FAIL"
export const INIT_NEW_INVOICES = "INIT_NEW_INVOICES"
export const INVOICES_SUCCESS = "INVOICES_SUCCESS"
export const INVOICES_FAIL = "INVOICES_FAIL"

export const INI_UPDATE_SETTINGS = "INI_UPDATE_SETTINGS"
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS"
export const UPDATE_SETTINGS_FAILURE = "UPDATE_SETTINGS_FAILURE"

// NAVIGATION
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"

// MODAL
export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"

// TRACKING WAYPOINTS
export const TOGGLE_WAYPOINT_SUCCESS = "TOGGLE_WAYPOINT_SUCCESS"
export const TOGGLE_WAYPOINT_ERROR = "TOGGLE_WAYPOINT_ERROR"
