export const FETCH_TRIPS = "FETCH_TRIPS"
export const AUTH_LOADING = "AUTH_LOADING"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"

export const PASSWORD_MATCH_ERROR = "PASSWORD_MATCH_ERROR"
export const PASSWORD_MATCH_SUCCESS = "PASSWORD_MATCH_SUCCESS"

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE"
