// AUTH
export const AUTH_LOADING = "AUTH_LOADING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE"
export const UPDATE_USER_IN_STORE = "UPDATE_USER_IN_STORE"

// INIT
export const ADD_TOKEN_TO_STATE = "ADD_TOKEN_TO_STATE"
export const QUERY_USER_BY_TOKEN = "QUERY_USER_BY_TOKEN"
export const QUERYING_USER_BY_TOKEN = "QUERYING_USER_BY_TOKEN"
export const QUERYING_USER_BY_TOKEN_SUCCESS = "QUERYING_USER_BY_TOKEN_SUCCESS"
export const QUERYING_USER_BY_TOKEN_ERROR = "QUERYING_USER_BY_TOKEN_ERROR"

// TRIPS
export const LOADING_TRIPS = "LOADING_TRIPS"
export const LOADING_TRIPS_SUCCESS = "LOADING_TRIPS_SUCCESS"
export const LOADING_TRIPS_ERROR = "LOADING_TRIPS_ERROR"
export const LOADING_ARCHIVED_TRIPS = "LOADING_ARCHIVED_TRIPS"
export const LOADING_ARCHIVED_TRIPS_SUCCESS = "LOADING_ARCHIVED_TRIPS_SUCCESS"
export const LOADING_ARCHIVED_TRIPS_ERROR = "LOADING_ARCHIVED_TRIPS_ERROR"
export const CREATING_TRIP = "CREATING_TRIP"
export const CREATING_TRIP_SUCCESS = "CREATING_TRIP_SUCCESS"
export const CREATING_TRIP_ERROR = "CREATING_TRIP_ERROR"
export const CREATING_WAYPOINT = "CREATING_WAYPOINT"
export const DELETING_TRIP = "DELETING_TRIP"
export const DELETING_TRIP_SUCCESS = "DELETING_TRIP_SUCCESS"
export const DELETING_TRIP_ERROR = "DELETING_TRIP_ERROR"
export const GET_SINGLE_TRIP = "GET_SINGLE_TRIP"
export const TOGGLE_ARCHIVE_TRIP = "TOGGLE_ARCHIVE_TRIP"
export const TOGGLE_ARCHIVE_TRIP_SUCCESS = "TOGGLE_ARCHIVE_TRIP_SUCCESS"
export const TOGGLE_ARCHIVE_TRIP_ERROR = "TOGGLE_ARCHIVE_TRIP_ERROR"
export const REPEAT_TRIP = "REPEAT_TRIP"
export const REPEAT_TRIP_SUCCESS = "REPEAT_TRIP_SUCCESS"
export const REPEAT_TRIP_ERROR = "REPEAT_TRIP_ERROR"
export const UPLOADING_TRIP_PIC = "UPLOADING_TRIP_PIC"
export const UPLOADING_TRIP_PIC_SUCCESS = "UPLOADING_TRIP_PIC_SUCCESS"
export const UPLOADING_TRIP_PIC_ERROR = "UPLOADING_TRIP_PIC_ERROR"

// BILLING
export const INIT_NEW_SUBSCRIPTION = "INIT_NEW_SUBSCRIPTION"
export const SUBSCRIBE_PENDING = "SUBSCRIBE_PENDING"
export const SUBSCRIBE_SUCCESS = "SUBSCRIBE_SUCCESS"
export const SUBSCRIBE_FAIL = "SUBSCRIBE_FAIL"
export const INIT_NEW_CANCELLATION = "INIT_NEW_CANCELLATION"
export const CANCEL_SUBSCRIPTION_SUCCESS = "CANCEL_SUBSCRIPTION_SUCCESS"
export const CANCEL_SUBSCRIPTION_FAIL = "CANCEL_SUBSCRIPTION_FAIL"
export const INIT_NEW_INVOICES = "INIT_NEW_INVOICES"
export const INVOICES_SUCCESS = "INVOICES_SUCCESS"
export const INVOICES_FAIL = "INVOICES_FAIL"

export const INI_UPDATE_SETTINGS = "INI_UPDATE_SETTINGS"
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS"
export const UPDATE_SETTINGS_FAILURE = "UPDATE_SETTINGS_FAILURE"

// NAVIGATION
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"

// MODAL
export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"
